FROM        python:3.7.15-alpine3.17

EXPOSE      8000
ENV         FLASK_APP=app.py

COPY        . . 
COPY        requirements.txt .

RUN         apk add --virtual .build-deps \
                build-base \
                libffi-dev
RUN         pip install -r requirements.txt

COPY        app.py .


CMD [ "flask", "run", "-h", "0.0.0.0", "-p", "8000", "--debugger", "--reload" ]

