name: Docker

on:
  push:
    tags:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        tag:
        - base
        - multi-stage
        dockerfile:
        - "dockerfile"
        - "dockerfile-multi-step"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Configure
    #   id: config
    #   run: |-
    #     NPROC=$(nproc)

    #     echo "NPROC=$NPROC" >> $GITHUB_ENV
    #     echo "NPROC=$NPROC" >> $GITHUB_OUTPUT
    #     echo "repo-owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
    #     echo "repo-name=${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_OUTPUT

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    #   with:
    #     platforms: linux/amd64, linux/arm64

    - name: Setup - Setup buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup - Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |-
          a901002666/${{ steps.config.outputs.repo-name }}-docker-101
        tags: |-
          type=raw,value=${{ matrix.tag }}

    - name: Build
      uses: docker/build-push-action@v3
      id: build
      with:
        context: "{{defaultContext}}:docker-101"
        file: ${{ matrix.dockerfile }}
        # platforms: linux/amd64,linux/arm64
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
